name = "Immersive Siege"
author = "Aaron Rine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6e3f6f04077a2a55db3ff0e052e18bcefb4212dcc09cd3c298cd0ecbb714a40"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"
