name = "Immersive Siege"
author = "Aaron Rine"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f778add3f4a68c11465512163cc0c125a4940c10391d916f127057d94a19be30"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"
