name = "Alex's Mobs"
filename = "alexsmobs-1.12.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3467/280/alexsmobs-1.12.1.jar"
hash-format = "murmur2"
hash = "2288821940"

[update]
[update.curseforge]
file-id = 3467280
project-id = 426558
