name = "Apotheosis"
filename = "Apotheosis-1.16.5-4.8.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3567/270/Apotheosis-1.16.5-4.8.4.jar"
hash-format = "murmur2"
hash = "1175972820"

[update]
[update.curseforge]
file-id = 3567270
project-id = 313970
