name = "Artifacts"
filename = "Artifacts-1.16.5-2.10.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3665/636/Artifacts-1.16.5-2.10.5.jar"
hash-format = "murmur2"
hash = "1383851963"

[update]
[update.curseforge]
file-id = 3665636
project-id = 312353
