name = "Chisels & Bits - For Forge"
filename = "chiselsandbits-1.0.63.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3593/643/chiselsandbits-1.0.63.jar"
hash-format = "murmur2"
hash = "105582602"

[update]
[update.curseforge]
file-id = 3593643
project-id = 231095
