name = "Corail Tombstone"
filename = "tombstone-6.7.3-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3649/155/tombstone-6.7.3-1.16.5.jar"
hash-format = "murmur2"
hash = "1419885945"

[update]
[update.curseforge]
file-id = 3649155
project-id = 243707
