name = "Curios API (Forge)"
filename = "curios-forge-1.16.5-4.0.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3661/903/curios-forge-1.16.5-4.0.8.1.jar"
hash-format = "murmur2"
hash = "3048731592"

[update]
[update.curseforge]
file-id = 3661903
project-id = 309927
