name = "Curios Quark Oddities Backpack"
filename = "CuriosQuarkOBP-1.16.5-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3199/963/CuriosQuarkOBP-1.16.5-1.0.2.jar"
hash-format = "murmur2"
hash = "2611594268"

[update]
[update.curseforge]
file-id = 3199963
project-id = 445208
