name = "GeckoLib"
filename = "geckolib-forge-1.16.5-3.0.65.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/666/geckolib-forge-1.16.5-3.0.65.jar"
hash-format = "murmur2"
hash = "1209965672"

[update]
[update.curseforge]
file-id = 3629666
project-id = 388172
