name = "Hats"
filename = "Hats-1.16.5-10.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/423/Hats-1.16.5-10.3.3.jar"
hash-format = "murmur2"
hash = "416188168"

[update]
[update.curseforge]
file-id = 3548423
project-id = 229073
