name = "Just Enough Items (JEI)"
filename = "jei-1.16.5-7.7.1.150.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3652/153/jei-1.16.5-7.7.1.150.jar"
hash-format = "murmur2"
hash = "846384164"

[update]
[update.curseforge]
file-id = 3652153
project-id = 238222
