name = "Just Enough Professions (JEP)"
filename = "JustEnoughProfessions-1.16.5-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3478/185/JustEnoughProfessions-1.16.5-1.2.2.jar"
hash-format = "murmur2"
hash = "1264078239"

[update]
[update.curseforge]
file-id = 3478185
project-id = 417645
