name = "Just Enough Effect Descriptions (JEED)"
filename = "jeed-1.16.5-1.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/185/jeed-1.16.5-1.6.jar"
hash-format = "murmur2"
hash = "928016087"

[update]
[update.curseforge]
file-id = 3541185
project-id = 532286
