name = "Macaw's Roofs"
filename = "mcw-roofs-2.1.0-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3616/173/mcw-roofs-2.1.0-mc1.16.5.jar"
hash-format = "murmur2"
hash = "1419075853"

[update]
[update.curseforge]
file-id = 3616173
project-id = 352039
