name = "Macaw's Bridges - Biome O' Plenty"
filename = "macawsbridgesbop-1.16.5-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/52/macawsbridgesbop-1.16.5-1.3.jar"
hash-format = "murmur2"
hash = "193219878"

[update]
[update.curseforge]
file-id = 3666052
project-id = 533382
