name = "Macaw's Paintings"
filename = "mcw-paintings-1.0.2-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3394/922/mcw-paintings-1.0.2-mc1.16.5.jar"
hash-format = "murmur2"
hash = "701531497"

[update]
[update.curseforge]
file-id = 3394922
project-id = 438116
