name = "Mowzie's Mobs"
filename = "mowziesmobs-1.5.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3626/519/mowziesmobs-1.5.22.jar"
hash-format = "murmur2"
hash = "3771823524"

[update]
[update.curseforge]
file-id = 3626519
project-id = 250498
