name = "Oh The Biomes You'll Go"
filename = "byg-1.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3485/79/byg-1.3.5.jar"
hash-format = "murmur2"
hash = "3878374771"

[update]
[update.curseforge]
file-id = 3485079
project-id = 247560
