name = "Pollution of the Realms"
filename = "AdPother-1.16.5-4.1.3.0-build.0206.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/767/AdPother-1.16.5-4.1.3.0-build.0206.jar"
hash-format = "murmur2"
hash = "1494061158"

[update]
[update.curseforge]
file-id = 3541767
project-id = 269973
