name = "Selene Lib"
filename = "selene-1.16.5-1.9.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3517/8/selene-1.16.5-1.9.0.jar"
hash-format = "murmur2"
hash = "3123819882"

[update]
[update.curseforge]
file-id = 3517008
project-id = 499980
