name = "Sophisticated Backpacks"
filename = "sophisticatedbackpacks-1.16.5-3.15.7.531.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3640/351/sophisticatedbackpacks-1.16.5-3.15.7.531.jar"
hash-format = "murmur2"
hash = "2983671609"

[update]
[update.curseforge]
file-id = 3640351
project-id = 422301
