name = "Tiny Redstone"
filename = "tinyredstone-1.16.5-1.13.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/423/tinyredstone-1.16.5-1.13.3.jar"
hash-format = "murmur2"
hash = "2229125482"

[update]
[update.curseforge]
file-id = 3651423
project-id = 453746
