name = "Xaero's World Map"
filename = "XaerosWorldMap_1.20.3.1_Forge_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3646/983/XaerosWorldMap_1.20.3.1_Forge_1.16.5.jar"
hash-format = "murmur2"
hash = "621188512"

[update]
[update.curseforge]
file-id = 3646983
project-id = 317780
